require("remap")
require("set")
require("plugins.lazy")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.blinkcmp")
require("plugins.keymaps")
require("plugins.theme")
require("plugins.cmdline")
require("plugins.rename")
require("plugins.statusbar")
require("plugins.smearcursor")
require("plugins.autoclose")
require("plugins.nvimtree")
require("plugins.autocompletion")

